export type ExerciseType = "vocab" | "mcq" | "fill" | "match" | "translate";

export interface VocabExercise {
  type: "vocab";
  word: string;
  translation: string;
  pronunciation: string;
}
export interface McqExercise {
  type: "mcq";
  question: string;
  options: string[];
  answer: string;
}
export interface FillExercise {
  type: "fill";
  sentence: string;
  answer: string;
  hint: string;
}
export interface MatchExercise {
  type: "match";
  pairs: { word: string; translation: string }[];
}
export interface TranslateExercise {
  type: "translate";
  source: string;
  answer: string;
  hint: string;
}

export type Exercise =
  | VocabExercise
  | McqExercise
  | FillExercise
  | MatchExercise
  | TranslateExercise;

export interface Level {
  id: number;
  unit: number;
  unitTitle: string;
  levelTitle: string;
  type: ExerciseType;
  xpReward: number;
  exercises: Exercise[];
}

export type Language = "japanese" | "mandarin" | "kannada";

// ============================================================
// JAPANESE CONTENT
// ============================================================
const japaneseUnits: { title: string; vocab: [string, string, string][] }[] = [
  {
    title: "Greetings",
    vocab: [
      ["こんにちは", "Hello", "Konnichiwa"],
      ["おはよう", "Good morning", "Ohayou"],
      ["こんばんは", "Good evening", "Konbanwa"],
      ["さようなら", "Goodbye", "Sayonara"],
      ["ありがとう", "Thank you", "Arigatou"],
      ["すみません", "Excuse me", "Sumimasen"],
      ["はい", "Yes", "Hai"],
      ["いいえ", "No", "Iie"],
      ["どうぞ", "Please/Here you go", "Douzo"],
      ["よろしく", "Nice to meet you", "Yoroshiku"],
    ],
  },
  {
    title: "Numbers 1–10",
    vocab: [
      ["いち", "One", "Ichi"],
      ["に", "Two", "Ni"],
      ["さん", "Three", "San"],
      ["し", "Four", "Shi"],
      ["ご", "Five", "Go"],
      ["ろく", "Six", "Roku"],
      ["なな", "Seven", "Nana"],
      ["はち", "Eight", "Hachi"],
      ["きゅう", "Nine", "Kyuu"],
      ["じゅう", "Ten", "Juu"],
    ],
  },
  {
    title: "Colors",
    vocab: [
      ["あか", "Red", "Aka"],
      ["あお", "Blue", "Ao"],
      ["きいろ", "Yellow", "Kiiro"],
      ["みどり", "Green", "Midori"],
      ["しろ", "White", "Shiro"],
      ["くろ", "Black", "Kuro"],
      ["ちゃいろ", "Brown", "Chairо"],
      ["むらさき", "Purple", "Murasaki"],
      ["ピンク", "Pink", "Pinku"],
      ["オレンジ", "Orange", "Orenji"],
    ],
  },
  {
    title: "Animals",
    vocab: [
      ["いぬ", "Dog", "Inu"],
      ["ねこ", "Cat", "Neko"],
      ["とり", "Bird", "Tori"],
      ["さかな", "Fish", "Sakana"],
      ["うさぎ", "Rabbit", "Usagi"],
      ["くま", "Bear", "Kuma"],
      ["ぞう", "Elephant", "Zou"],
      ["しし", "Lion", "Shishi"],
      ["さる", "Monkey", "Saru"],
      ["うま", "Horse", "Uma"],
    ],
  },
  {
    title: "Food & Drink",
    vocab: [
      ["ごはん", "Rice", "Gohan"],
      ["みず", "Water", "Mizu"],
      ["おちゃ", "Tea", "Ocha"],
      ["パン", "Bread", "Pan"],
      ["たまご", "Egg", "Tamago"],
      ["さかな", "Fish", "Sakana"],
      ["にく", "Meat", "Niku"],
      ["やさい", "Vegetable", "Yasai"],
      ["くだもの", "Fruit", "Kudamono"],
      ["ラーメン", "Ramen", "Raamen"],
    ],
  },
  {
    title: "Family",
    vocab: [
      ["おとうさん", "Father", "Otousan"],
      ["おかあさん", "Mother", "Okaasan"],
      ["おにいさん", "Elder brother", "Oniisan"],
      ["おねえさん", "Elder sister", "Oneesan"],
      ["いもうと", "Younger sister", "Imouto"],
      ["おとうと", "Younger brother", "Otouto"],
      ["おじいさん", "Grandfather", "Ojiisan"],
      ["おばあさん", "Grandmother", "Obaasan"],
      ["こども", "Child", "Kodomo"],
      ["かぞく", "Family", "Kazoku"],
    ],
  },
  {
    title: "Body Parts",
    vocab: [
      ["あたま", "Head", "Atama"],
      ["め", "Eyes", "Me"],
      ["はな", "Nose", "Hana"],
      ["くち", "Mouth", "Kuchi"],
      ["て", "Hand", "Te"],
      ["あし", "Foot/Leg", "Ashi"],
      ["からだ", "Body", "Karada"],
      ["かみ", "Hair", "Kami"],
      ["みみ", "Ear", "Mimi"],
      ["かた", "Shoulder", "Kata"],
    ],
  },
  {
    title: "Weather",
    vocab: [
      ["はれ", "Sunny", "Hare"],
      ["くもり", "Cloudy", "Kumori"],
      ["あめ", "Rain", "Ame"],
      ["ゆき", "Snow", "Yuki"],
      ["かぜ", "Wind", "Kaze"],
      ["あつい", "Hot", "Atsui"],
      ["さむい", "Cold", "Samui"],
      ["てんき", "Weather", "Tenki"],
      ["かみなり", "Thunder", "Kaminari"],
      ["にじ", "Rainbow", "Niji"],
    ],
  },
  {
    title: "Time",
    vocab: [
      ["いちじ", "One o'clock", "Ichiji"],
      ["にじ", "Two o'clock", "Niji"],
      ["ごぜん", "Morning/AM", "Gozen"],
      ["ごご", "Afternoon/PM", "Gogo"],
      ["いま", "Now", "Ima"],
      ["きょう", "Today", "Kyou"],
      ["あした", "Tomorrow", "Ashita"],
      ["きのう", "Yesterday", "Kinou"],
      ["まいにち", "Everyday", "Mainichi"],
      ["じかん", "Time", "Jikan"],
    ],
  },
  {
    title: "Days of the Week",
    vocab: [
      ["にちようび", "Sunday", "Nichiyoubi"],
      ["げつようび", "Monday", "Getsuyoubi"],
      ["かようび", "Tuesday", "Kayoubi"],
      ["すいようび", "Wednesday", "Suiyoubi"],
      ["もくようび", "Thursday", "Mokuyoubi"],
      ["きんようび", "Friday", "Kin'youbi"],
      ["どようび", "Saturday", "Doyoubi"],
      ["しゅうまつ", "Weekend", "Shuumatsu"],
      ["へいじつ", "Weekday", "Heijitsu"],
      ["らいしゅう", "Next week", "Raishuu"],
    ],
  },
  {
    title: "Months",
    vocab: [
      ["いちがつ", "January", "Ichigatsu"],
      ["にがつ", "February", "Nigatsu"],
      ["さんがつ", "March", "Sangatsu"],
      ["しがつ", "April", "Shigatsu"],
      ["ごがつ", "May", "Gogatsu"],
      ["ろくがつ", "June", "Rokugatsu"],
      ["しちがつ", "July", "Shichigatsu"],
      ["はちがつ", "August", "Hachigatsu"],
      ["くがつ", "September", "Kugatsu"],
      ["じゅうがつ", "October", "Juugatsu"],
    ],
  },
  {
    title: "Seasons",
    vocab: [
      ["はる", "Spring", "Haru"],
      ["なつ", "Summer", "Natsu"],
      ["あき", "Autumn", "Aki"],
      ["ふゆ", "Winter", "Fuyu"],
      ["きせつ", "Season", "Kisetsu"],
      ["あたたかい", "Warm", "Atatakai"],
      ["すずしい", "Cool", "Suzushii"],
      ["さくら", "Cherry blossom", "Sakura"],
      ["もみじ", "Autumn leaves", "Momiji"],
      ["ゆきだるま", "Snowman", "Yukidaruma"],
    ],
  },
  {
    title: "Clothing",
    vocab: [
      ["シャツ", "Shirt", "Shatsu"],
      ["ズボン", "Pants", "Zubon"],
      ["くつ", "Shoes", "Kutsu"],
      ["ぼうし", "Hat", "Boushi"],
      ["コート", "Coat", "Kooto"],
      ["ドレス", "Dress", "Doresu"],
      ["くつした", "Socks", "Kutsushita"],
      ["マフラー", "Scarf", "Mafuraa"],
      ["てぶくろ", "Gloves", "Tebukuro"],
      ["スーツ", "Suit", "Suutsu"],
    ],
  },
  {
    title: "Home & Rooms",
    vocab: [
      ["いえ", "House", "Ie"],
      ["へや", "Room", "Heya"],
      ["だいどころ", "Kitchen", "Daidokoro"],
      ["リビング", "Living room", "Ribingu"],
      ["しんしつ", "Bedroom", "Shinshitsu"],
      ["おふろ", "Bathroom", "Ofuro"],
      ["まど", "Window", "Mado"],
      ["ドア", "Door", "Doa"],
      ["テーブル", "Table", "Teeburu"],
      ["いす", "Chair", "Isu"],
    ],
  },
  {
    title: "School",
    vocab: [
      ["がっこう", "School", "Gakkou"],
      ["せんせい", "Teacher", "Sensei"],
      ["がくせい", "Student", "Gakusei"],
      ["ほん", "Book", "Hon"],
      ["えんぴつ", "Pencil", "Enpitsu"],
      ["きょうしつ", "Classroom", "Kyoushitsu"],
      ["べんきょう", "Study", "Benkyou"],
      ["しけん", "Exam", "Shiken"],
      ["せいと", "Pupil", "Seito"],
      ["そつぎょう", "Graduation", "Sotsugyou"],
    ],
  },
  {
    title: "Work & Jobs",
    vocab: [
      ["しごと", "Work", "Shigoto"],
      ["かいしゃ", "Company", "Kaisha"],
      ["いしゃ", "Doctor", "Isha"],
      ["きょうし", "Teacher", "Kyoushi"],
      ["エンジニア", "Engineer", "Enjinia"],
      ["まねーじゃー", "Manager", "Maneejaa"],
      ["かいけい", "Accounting", "Kaikei"],
      ["きゅうりょう", "Salary", "Kyuuryou"],
      ["かいぎ", "Meeting", "Kaigi"],
      ["でんわ", "Phone", "Denwa"],
    ],
  },
  {
    title: "Transport",
    vocab: [
      ["でんしゃ", "Train", "Densha"],
      ["バス", "Bus", "Basu"],
      ["じてんしゃ", "Bicycle", "Jitensha"],
      ["くるま", "Car", "Kuruma"],
      ["ひこうき", "Airplane", "Hikouki"],
      ["ふね", "Ship", "Fune"],
      ["えき", "Station", "Eki"],
      ["くうこう", "Airport", "Kuukou"],
      ["ちかてつ", "Subway", "Chikatetsu"],
      ["タクシー", "Taxi", "Takushii"],
    ],
  },
  {
    title: "Shopping",
    vocab: [
      ["みせ", "Shop", "Mise"],
      ["かいもの", "Shopping", "Kaimono"],
      ["ねだん", "Price", "Nedan"],
      ["やすい", "Cheap", "Yasui"],
      ["たかい", "Expensive", "Takai"],
      ["おつり", "Change", "Otsuri"],
      ["レシート", "Receipt", "Reshiito"],
      ["ふくろ", "Bag", "Fukuro"],
      ["セール", "Sale", "Seeru"],
      ["かう", "To buy", "Kau"],
    ],
  },
  {
    title: "Restaurant",
    vocab: [
      ["レストラン", "Restaurant", "Resutoran"],
      ["メニュー", "Menu", "Menyuu"],
      ["ちゅうもん", "Order", "Chuumon"],
      ["おいしい", "Delicious", "Oishii"],
      ["からい", "Spicy", "Karai"],
      ["あまい", "Sweet", "Amai"],
      ["しおからい", "Salty", "Shiokarai"],
      ["かんじょう", "Bill", "Kanjou"],
      ["テーブル", "Table", "Teeburu"],
      ["ウェイター", "Waiter", "Weitaa"],
    ],
  },
  {
    title: "Hobbies",
    vocab: [
      ["えいが", "Movie", "Eiga"],
      ["おんがく", "Music", "Ongaku"],
      ["りょこう", "Travel", "Ryokou"],
      ["りょうり", "Cooking", "Ryouri"],
      ["スポーツ", "Sports", "Supootsu"],
      ["よむ", "To read", "Yomu"],
      ["かく", "To write/draw", "Kaku"],
      ["うたう", "To sing", "Utau"],
      ["あそぶ", "To play", "Asobu"],
      ["さんぽ", "Walk/Stroll", "Sanpo"],
    ],
  },
  {
    title: "Nature",
    vocab: [
      ["やま", "Mountain", "Yama"],
      ["うみ", "Sea", "Umi"],
      ["かわ", "River", "Kawa"],
      ["もり", "Forest", "Mori"],
      ["はな", "Flower", "Hana"],
      ["き", "Tree", "Ki"],
      ["そら", "Sky", "Sora"],
      ["つき", "Moon", "Tsuki"],
      ["ほし", "Star", "Hoshi"],
      ["たいよう", "Sun", "Taiyou"],
    ],
  },
  {
    title: "Emotions",
    vocab: [
      ["うれしい", "Happy", "Ureshii"],
      ["かなしい", "Sad", "Kanashii"],
      ["おこる", "Angry", "Okoru"],
      ["こわい", "Scary/Afraid", "Kowai"],
      ["たのしい", "Fun", "Tanoshii"],
      ["つかれた", "Tired", "Tsukareta"],
      ["びっくり", "Surprised", "Bikkuri"],
      ["はずかしい", "Embarrassed", "Hazukashii"],
      ["ねむい", "Sleepy", "Nemui"],
      ["げんき", "Energetic/Healthy", "Genki"],
    ],
  },
  {
    title: "Health & Body",
    vocab: [
      ["びょういん", "Hospital", "Byouin"],
      ["くすり", "Medicine", "Kusuri"],
      ["いたい", "Painful", "Itai"],
      ["びょうき", "Illness", "Byouki"],
      ["かぜ", "Cold (illness)", "Kaze"],
      ["ねつ", "Fever", "Netsu"],
      ["けが", "Injury", "Kega"],
      ["てあて", "Treatment", "Teate"],
      ["よぼう", "Prevention", "Yobou"],
      ["けんこう", "Health", "Kenkou"],
    ],
  },
  {
    title: "Emergency",
    vocab: [
      ["たすけて", "Help!", "Tasukete"],
      ["きゅうきゅうしゃ", "Ambulance", "Kyuukyuusha"],
      ["けいさつ", "Police", "Keisatsu"],
      ["かじ", "Fire", "Kaji"],
      ["きけん", "Danger", "Kiken"],
      ["あんぜん", "Safe", "Anzen"],
      ["ひじょうぐち", "Emergency exit", "Hijouguchi"],
      ["でんわ", "Phone", "Denwa"],
      ["まよった", "Lost", "Mayotta"],
      ["おねがい", "Please (help)", "Onegai"],
    ],
  },
  {
    title: "Japanese Culture",
    vocab: [
      ["おまつり", "Festival", "Omatsuri"],
      ["じんじゃ", "Shrine", "Jinja"],
      ["おてら", "Temple", "Otera"],
      ["きもの", "Kimono", "Kimono"],
      ["おりがみ", "Origami", "Origami"],
      ["すもう", "Sumo", "Sumou"],
      ["さどう", "Tea ceremony", "Sadou"],
      ["かぶき", "Kabuki", "Kabuki"],
      ["まんが", "Manga", "Manga"],
      ["アニメ", "Anime", "Anime"],
    ],
  },
  {
    title: "Honorifics",
    vocab: [
      ["さん", "Mr./Ms. (polite)", "San"],
      ["くん", "Boy/Junior", "Kun"],
      ["ちゃん", "Cute/Familiar", "Chan"],
      ["せんせい", "Teacher (honorific)", "Sensei"],
      ["けいご", "Polite language", "Keigo"],
      ["ていねい", "Polite", "Teinei"],
      ["おじぎ", "Bow", "Ojigi"],
      ["おかげさまで", "Thanks to you", "Okagesama de"],
      ["いただきます", "Before eating", "Itadakimasu"],
      ["ごちそうさま", "After eating", "Gochisousama"],
    ],
  },
  {
    title: "Basic Kanji 1",
    vocab: [
      ["日", "Sun/Day", "Nichi/Hi"],
      ["月", "Moon/Month", "Tsuki/Getsu"],
      ["火", "Fire", "Hi/Ka"],
      ["水", "Water", "Mizu/Sui"],
      ["木", "Tree/Wood", "Ki/Moku"],
      ["金", "Gold/Money", "Kane/Kin"],
      ["土", "Earth/Soil", "Tsuchi/Do"],
      ["山", "Mountain", "Yama/San"],
      ["川", "River", "Kawa/Sen"],
      ["田", "Rice field", "Ta/Den"],
    ],
  },
  {
    title: "Basic Kanji 2",
    vocab: [
      ["人", "Person", "Hito/Jin"],
      ["口", "Mouth", "Kuchi/Kou"],
      ["手", "Hand", "Te/Shu"],
      ["目", "Eye", "Me/Moku"],
      ["耳", "Ear", "Mimi/Ji"],
      ["足", "Foot/Leg", "Ashi/Soku"],
      ["力", "Power", "Chikara/Ryoku"],
      ["心", "Heart/Mind", "Kokoro/Shin"],
      ["上", "Up/Above", "Ue/Jou"],
      ["下", "Down/Below", "Shita/Ka"],
    ],
  },
  {
    title: "Verbs 1",
    vocab: [
      ["たべる", "To eat", "Taberu"],
      ["のむ", "To drink", "Nomu"],
      ["いく", "To go", "Iku"],
      ["くる", "To come", "Kuru"],
      ["みる", "To see/watch", "Miru"],
      ["きく", "To listen", "Kiku"],
      ["はなす", "To speak", "Hanasu"],
      ["かく", "To write", "Kaku"],
      ["よむ", "To read", "Yomu"],
      ["する", "To do", "Suru"],
    ],
  },
  {
    title: "Adjectives 1",
    vocab: [
      ["おおきい", "Big", "Ookii"],
      ["ちいさい", "Small", "Chiisai"],
      ["あたらしい", "New", "Atarashii"],
      ["ふるい", "Old", "Furui"],
      ["いい", "Good", "Ii"],
      ["わるい", "Bad", "Warui"],
      ["はやい", "Fast", "Hayai"],
      ["おそい", "Slow", "Osoi"],
      ["むずかしい", "Difficult", "Muzukashii"],
      ["やさしい", "Easy/Kind", "Yasashii"],
    ],
  },
  {
    title: "Directions",
    vocab: [
      ["みぎ", "Right", "Migi"],
      ["ひだり", "Left", "Hidari"],
      ["まえ", "Front", "Mae"],
      ["うしろ", "Back", "Ushiro"],
      ["まっすぐ", "Straight", "Massugu"],
      ["ちかく", "Near", "Chikaku"],
      ["とおい", "Far", "Tooi"],
      ["きた", "North", "Kita"],
      ["みなみ", "South", "Minami"],
      ["ひがし", "East", "Higashi"],
    ],
  },
  {
    title: "Particles & Grammar",
    vocab: [
      ["は", "Topic marker", "Wa"],
      ["が", "Subject marker", "Ga"],
      ["を", "Object marker", "Wo"],
      ["に", "Direction/Time", "Ni"],
      ["で", "Location/By", "De"],
      ["の", "Possession", "No"],
      ["と", "And/With", "To"],
      ["も", "Also/Too", "Mo"],
      ["から", "From/Because", "Kara"],
      ["まで", "Until/To", "Made"],
    ],
  },
  {
    title: "Numbers 11–100",
    vocab: [
      ["じゅういち", "Eleven", "Juuichi"],
      ["じゅうに", "Twelve", "Juuni"],
      ["にじゅう", "Twenty", "Nijuu"],
      ["さんじゅう", "Thirty", "Sanjuu"],
      ["よんじゅう", "Forty", "Yonjuu"],
      ["ごじゅう", "Fifty", "Gojuu"],
      ["ろくじゅう", "Sixty", "Rokujuu"],
      ["ななじゅう", "Seventy", "Nanajuu"],
      ["はちじゅう", "Eighty", "Hachijuu"],
      ["きゅうじゅう", "Ninety", "Kyuujuu"],
    ],
  },
  {
    title: "Sentence Patterns 1",
    vocab: [
      ["〜です", "Is/Am (polite)", "~desu"],
      ["〜ます", "Verb ending (polite)", "~masu"],
      ["〜ません", "Negative verb", "~masen"],
      ["〜でした", "Was (past)", "~deshita"],
      ["〜ましょう", "Let's ~", "~mashou"],
      ["〜てください", "Please do ~", "~te kudasai"],
      ["〜たい", "Want to ~", "~tai"],
      ["〜ながら", "While doing ~", "~nagara"],
      ["〜から", "Because ~", "~kara"],
      ["〜けど", "But/However", "~kedo"],
    ],
  },
  {
    title: "Sentence Patterns 2",
    vocab: [
      ["〜と思います", "I think ~", "~to omoimasu"],
      ["〜かもしれません", "Maybe ~", "~kamo shiremasen"],
      ["〜なければなりません", "Must ~", "~nakereba narimasen"],
      ["〜てもいいですか", "May I ~?", "~te mo ii desu ka"],
      ["〜てはいけません", "Must not ~", "~te wa ikemasen"],
      ["〜ようにしています", "Trying to ~", "~you ni shite imasu"],
      ["〜ために", "In order to ~", "~tame ni"],
      ["〜によると", "According to ~", "~ni yoru to"],
      ["〜おかげで", "Thanks to ~", "~okage de"],
      ["〜せいで", "Because of (negative) ~", "~sei de"],
    ],
  },
  {
    title: "Tech & Modern",
    vocab: [
      ["スマホ", "Smartphone", "Sumaho"],
      ["パソコン", "Computer", "Pasokon"],
      ["インターネット", "Internet", "Intaanetto"],
      ["アプリ", "App", "Apuri"],
      ["メール", "Email", "Meeru"],
      ["SNS", "Social media", "Esu-En-Esu"],
      ["ゲーム", "Game", "Geemu"],
      ["チャット", "Chat", "Chatto"],
      ["オンライン", "Online", "Onrain"],
      ["ダウンロード", "Download", "Daunroodo"],
    ],
  },
  {
    title: "Travel",
    vocab: [
      ["りょかん", "Japanese inn", "Ryokan"],
      ["おみやげ", "Souvenir", "Omiyage"],
      ["かんこう", "Sightseeing", "Kankou"],
      ["パスポート", "Passport", "Pasupooto"],
      ["ホテル", "Hotel", "Hoteru"],
      ["チェックイン", "Check in", "Chekkuin"],
      ["ちず", "Map", "Chizu"],
      ["きっぷ", "Ticket", "Kippu"],
      ["バゲージ", "Baggage", "Bageeji"],
      ["まちがえる", "To make a mistake", "Machigaeru"],
    ],
  },
  {
    title: "Advanced Verbs",
    vocab: [
      ["おぼえる", "To memorize", "Oboeru"],
      ["わすれる", "To forget", "Wasureru"],
      ["おしえる", "To teach", "Oshieru"],
      ["ならう", "To learn", "Narau"],
      ["わかる", "To understand", "Wakaru"],
      ["しる", "To know", "Shiru"],
      ["かんがえる", "To think", "Kangaeru"],
      ["きめる", "To decide", "Kimeru"],
      ["かえる", "To change", "Kaeru"],
      ["つかう", "To use", "Tsukau"],
    ],
  },
  {
    title: "Advanced Adjectives",
    vocab: [
      ["ふしぎ", "Mysterious/Strange", "Fushigi"],
      ["すばらしい", "Wonderful", "Subarashii"],
      ["たいせつ", "Important", "Taisetsu"],
      ["めずらしい", "Rare", "Mezurashii"],
      ["かわいい", "Cute", "Kawaii"],
      ["かっこいい", "Cool", "Kakkoii"],
      ["うつくしい", "Beautiful", "Utsukushii"],
      ["きびしい", "Strict", "Kibishii"],
      ["おとなしい", "Quiet/Gentle", "Otonashii"],
      ["まじめ", "Serious", "Majime"],
    ],
  },
  {
    title: "Society & News",
    vocab: [
      ["せいじ", "Politics", "Seiji"],
      ["けいざい", "Economy", "Keizai"],
      ["しゃかい", "Society", "Shakai"],
      ["もんだい", "Problem", "Mondai"],
      ["かいけつ", "Resolution", "Kaiketsu"],
      ["かんきょう", "Environment", "Kankyou"],
      ["へいわ", "Peace", "Heiwa"],
      ["じゆう", "Freedom", "Jiyuu"],
      ["びょうどう", "Equality", "Byoudou"],
      ["しんぽ", "Progress", "Shinpo"],
    ],
  },
  {
    title: "Literature & Arts",
    vocab: [
      ["はいく", "Haiku", "Haiku"],
      ["しょうせつ", "Novel", "Shousetsu"],
      ["し", "Poetry", "Shi"],
      ["えいが", "Film", "Eiga"],
      ["びじゅつ", "Fine arts", "Bijutsu"],
      ["ちょうこく", "Sculpture", "Choukoku"],
      ["おどり", "Dance", "Odori"],
      ["えんそう", "Performance", "Ensou"],
      ["かなでる", "To play music", "Kanaderu"],
      ["ひょうげん", "Expression", "Hyougen"],
    ],
  },
  {
    title: "Science",
    vocab: [
      ["かがく", "Science", "Kagaku"],
      ["かがくしゃ", "Scientist", "Kagakusha"],
      ["じっけん", "Experiment", "Jikken"],
      ["けっか", "Result", "Kekka"],
      ["かせつ", "Hypothesis", "Kasetsu"],
      ["でんき", "Electricity", "Denki"],
      ["じりょく", "Magnetism", "Jiryoku"],
      ["じゅうりょく", "Gravity", "Juuryoku"],
      ["さんそ", "Oxygen", "Sanso"],
      ["すいそ", "Hydrogen", "Suiso"],
    ],
  },
  {
    title: "Advanced Grammar 1",
    vocab: [
      ["〜にしたがって", "According to/As ~", "~ni shitagatte"],
      ["〜をはじめ", "Starting with ~", "~wo hajime"],
      ["〜に反して", "Contrary to ~", "~ni hanshite"],
      ["〜とともに", "Together with ~", "~to tomoni"],
      ["〜にもかかわらず", "Despite ~", "~ni mo kakawarazu"],
      ["〜をもとに", "Based on ~", "~wo moto ni"],
      ["〜に際して", "On the occasion of ~", "~ni saishite"],
      ["〜を通じて", "Through/Via ~", "~wo tsuujite"],
      ["〜に伴って", "Along with ~", "~ni tomonatte"],
      ["〜として", "As ~ / In the role of", "~to shite"],
    ],
  },
  {
    title: "Advanced Grammar 2",
    vocab: [
      ["〜ばかりでなく", "Not only ~ but also", "~bakari de naku"],
      ["〜さえ〜ば", "If only ~, then", "~sae ~ba"],
      ["〜ものの", "Although ~", "~mono no"],
      ["〜わけがない", "There is no way ~", "~wake ga nai"],
      ["〜に違いない", "Must be ~", "~ni chigai nai"],
      ["〜に過ぎない", "Nothing more than ~", "~ni suginai"],
      ["〜に当たって", "When doing ~", "~ni atatte"],
      ["〜向けに", "Aimed at ~", "~muke ni"],
      ["〜によって", "Depending on / By ~", "~ni yotte"],
      ["〜ことになっている", "It is decided that ~", "~koto ni natte iru"],
    ],
  },
  {
    title: "JLPT N4 Vocab",
    vocab: [
      ["決める", "To decide", "Kimeru"],
      ["見つける", "To find", "Mitsukeru"],
      ["驚く", "To be surprised", "Odoroku"],
      ["伝える", "To convey", "Tsutaeru"],
      ["集める", "To collect", "Atsumeru"],
      ["調べる", "To investigate", "Shiraberu"],
      ["続ける", "To continue", "Tsuzukeru"],
      ["止める", "To stop", "Tomeru"],
      ["試みる", "To try", "Kokoromiru"],
      ["確かめる", "To confirm", "Tashikameru"],
    ],
  },
  {
    title: "JLPT N3 Vocab",
    vocab: [
      ["影響", "Influence", "Eikyou"],
      ["状況", "Situation", "Joukyou"],
      ["関係", "Relationship", "Kankei"],
      ["問題", "Problem", "Mondai"],
      ["可能性", "Possibility", "Kanousei"],
      ["必要", "Necessary", "Hitsuyou"],
      ["重要", "Important", "Juuyou"],
      ["実際", "In reality", "Jissai"],
      ["結果", "Result", "Kekka"],
      ["原因", "Cause", "Genin"],
    ],
  },
  {
    title: "JLPT N2 Vocab",
    vocab: [
      ["傾向", "Tendency", "Keikou"],
      ["観点", "Viewpoint", "Kanten"],
      ["役割", "Role", "Yakuwari"],
      ["前提", "Premise", "Zentei"],
      ["概念", "Concept", "Gainen"],
      ["具体的", "Concrete", "Gutaiteki"],
      ["抽象的", "Abstract", "Chuushouteki"],
      ["批判", "Criticism", "Hihan"],
      ["評価", "Evaluation", "Hyouka"],
      ["矛盾", "Contradiction", "Mujun"],
    ],
  },
  {
    title: "Mastery Review",
    vocab: [
      ["語彙", "Vocabulary", "Goi"],
      ["文法", "Grammar", "Bunpou"],
      ["発音", "Pronunciation", "Hatsuon"],
      ["読解", "Reading comprehension", "Dokkai"],
      ["聴解", "Listening comprehension", "Choukai"],
      ["作文", "Essay/Composition", "Sakubun"],
      ["会話", "Conversation", "Kaiwa"],
      ["翻訳", "Translation", "Hon'yaku"],
      ["習得", "Acquisition", "Shuutoku"],
      ["流暢", "Fluent", "Ryuuchou"],
    ],
  },
];

const mandarinUnits: { title: string; vocab: [string, string, string][] }[] = [
  {
    title: "Greetings",
    vocab: [
      ["你好", "Hello", "Nǐ hǎo"],
      ["早上好", "Good morning", "Zǎoshang hǎo"],
      ["晚上好", "Good evening", "Wǎnshang hǎo"],
      ["再见", "Goodbye", "Zàijiàn"],
      ["谢谢", "Thank you", "Xièxiè"],
      ["不客气", "You're welcome", "Bú kèqi"],
      ["对不起", "Sorry", "Duìbuqǐ"],
      ["没关系", "No problem", "Méiguānxi"],
      ["请", "Please", "Qǐng"],
      ["好的", "Okay", "Hǎo de"],
    ],
  },
  {
    title: "Numbers",
    vocab: [
      ["一", "One", "Yī"],
      ["二", "Two", "Èr"],
      ["三", "Three", "Sān"],
      ["四", "Four", "Sì"],
      ["五", "Five", "Wǔ"],
      ["六", "Six", "Liù"],
      ["七", "Seven", "Qī"],
      ["八", "Eight", "Bā"],
      ["九", "Nine", "Jiǔ"],
      ["十", "Ten", "Shí"],
    ],
  },
  {
    title: "Colors",
    vocab: [
      ["红色", "Red", "Hóngsè"],
      ["蓝色", "Blue", "Lánsè"],
      ["黄色", "Yellow", "Huángsè"],
      ["绿色", "Green", "Lǜsè"],
      ["白色", "White", "Báisè"],
      ["黑色", "Black", "Hēisè"],
      ["紫色", "Purple", "Zǐsè"],
      ["橙色", "Orange", "Chéngsè"],
      ["粉色", "Pink", "Fěnsè"],
      ["棕色", "Brown", "Zōngsè"],
    ],
  },
  {
    title: "Animals",
    vocab: [
      ["狗", "Dog", "Gǒu"],
      ["猫", "Cat", "Māo"],
      ["鸟", "Bird", "Niǎo"],
      ["鱼", "Fish", "Yú"],
      ["兔子", "Rabbit", "Tùzi"],
      ["熊", "Bear", "Xióng"],
      ["大象", "Elephant", "Dàxiàng"],
      ["狮子", "Lion", "Shīzi"],
      ["猴子", "Monkey", "Hóuzi"],
      ["马", "Horse", "Mǎ"],
    ],
  },
  {
    title: "Food & Drink",
    vocab: [
      ["米饭", "Rice", "Mǐfàn"],
      ["水", "Water", "Shuǐ"],
      ["茶", "Tea", "Chá"],
      ["面包", "Bread", "Miànbāo"],
      ["鸡蛋", "Egg", "Jīdàn"],
      ["鱼", "Fish", "Yú"],
      ["肉", "Meat", "Ròu"],
      ["蔬菜", "Vegetables", "Shūcài"],
      ["水果", "Fruit", "Shuǐguǒ"],
      ["面条", "Noodles", "Miàntiáo"],
    ],
  },
  {
    title: "Family",
    vocab: [
      ["爸爸", "Father", "Bàba"],
      ["妈妈", "Mother", "Māma"],
      ["哥哥", "Elder brother", "Gēge"],
      ["姐姐", "Elder sister", "Jiějie"],
      ["弟弟", "Younger brother", "Dìdi"],
      ["妹妹", "Younger sister", "Mèimei"],
      ["爷爷", "Grandfather (paternal)", "Yéye"],
      ["奶奶", "Grandmother (paternal)", "Nǎinai"],
      ["孩子", "Child", "Háizi"],
      ["家庭", "Family", "Jiātíng"],
    ],
  },
  {
    title: "Body Parts",
    vocab: [
      ["头", "Head", "Tóu"],
      ["眼睛", "Eyes", "Yǎnjīng"],
      ["鼻子", "Nose", "Bízi"],
      ["嘴巴", "Mouth", "Zuǐbā"],
      ["手", "Hand", "Shǒu"],
      ["脚", "Foot", "Jiǎo"],
      ["身体", "Body", "Shēntǐ"],
      ["头发", "Hair", "Tóufà"],
      ["耳朵", "Ear", "Ěrduǒ"],
      ["肩膀", "Shoulder", "Jiānbǎng"],
    ],
  },
  {
    title: "Weather",
    vocab: [
      ["晴天", "Sunny", "Qíngtiān"],
      ["阴天", "Cloudy", "Yīntiān"],
      ["下雨", "Raining", "Xià yǔ"],
      ["下雪", "Snowing", "Xià xuě"],
      ["风", "Wind", "Fēng"],
      ["热", "Hot", "Rè"],
      ["冷", "Cold", "Lěng"],
      ["天气", "Weather", "Tiānqì"],
      ["雷", "Thunder", "Léi"],
      ["彩虹", "Rainbow", "Cǎihóng"],
    ],
  },
  {
    title: "Time",
    vocab: [
      ["一点", "One o'clock", "Yī diǎn"],
      ["两点", "Two o'clock", "Liǎng diǎn"],
      ["上午", "Morning/AM", "Shàngwǔ"],
      ["下午", "Afternoon/PM", "Xiàwǔ"],
      ["现在", "Now", "Xiànzài"],
      ["今天", "Today", "Jīntiān"],
      ["明天", "Tomorrow", "Míngtiān"],
      ["昨天", "Yesterday", "Zuótiān"],
      ["每天", "Everyday", "Měitiān"],
      ["时间", "Time", "Shíjiān"],
    ],
  },
  {
    title: "Days of the Week",
    vocab: [
      ["星期天", "Sunday", "Xīngqītiān"],
      ["星期一", "Monday", "Xīngqīyī"],
      ["星期二", "Tuesday", "Xīngqīèr"],
      ["星期三", "Wednesday", "Xīngqīsān"],
      ["星期四", "Thursday", "Xīngqīsì"],
      ["星期五", "Friday", "Xīngqīwǔ"],
      ["星期六", "Saturday", "Xīngqīliù"],
      ["周末", "Weekend", "Zhōumò"],
      ["工作日", "Weekday", "Gōngzuòrì"],
      ["下周", "Next week", "Xià zhōu"],
    ],
  },
  {
    title: "Months",
    vocab: [
      ["一月", "January", "Yīyuè"],
      ["二月", "February", "Èryuè"],
      ["三月", "March", "Sānyuè"],
      ["四月", "April", "Sìyuè"],
      ["五月", "May", "Wǔyuè"],
      ["六月", "June", "Liùyuè"],
      ["七月", "July", "Qīyuè"],
      ["八月", "August", "Bāyuè"],
      ["九月", "September", "Jiǔyuè"],
      ["十月", "October", "Shíyuè"],
    ],
  },
  {
    title: "Seasons",
    vocab: [
      ["春天", "Spring", "Chūntiān"],
      ["夏天", "Summer", "Xiàtiān"],
      ["秋天", "Autumn", "Qiūtiān"],
      ["冬天", "Winter", "Dōngtiān"],
      ["季节", "Season", "Jìjié"],
      ["温暖", "Warm", "Wēnnuǎn"],
      ["凉爽", "Cool", "Liángshuǎng"],
      ["樱花", "Cherry blossom", "Yīnghuā"],
      ["枫叶", "Maple leaves", "Fēngyè"],
      ["雪人", "Snowman", "Xuěrén"],
    ],
  },
  {
    title: "Clothing",
    vocab: [
      ["衬衫", "Shirt", "Chènshān"],
      ["裤子", "Pants", "Kùzi"],
      ["鞋子", "Shoes", "Xiézi"],
      ["帽子", "Hat", "Màozi"],
      ["外套", "Coat", "Wàitào"],
      ["裙子", "Dress/Skirt", "Qúnzi"],
      ["袜子", "Socks", "Wàzi"],
      ["围巾", "Scarf", "Wéijīn"],
      ["手套", "Gloves", "Shǒutào"],
      ["西装", "Suit", "Xīzhuāng"],
    ],
  },
  {
    title: "Home & Rooms",
    vocab: [
      ["家", "Home", "Jiā"],
      ["房间", "Room", "Fángjiān"],
      ["厨房", "Kitchen", "Chúfáng"],
      ["客厅", "Living room", "Kètīng"],
      ["卧室", "Bedroom", "Wòshì"],
      ["浴室", "Bathroom", "Yùshì"],
      ["窗户", "Window", "Chuānghù"],
      ["门", "Door", "Mén"],
      ["桌子", "Table", "Zhuōzi"],
      ["椅子", "Chair", "Yǐzi"],
    ],
  },
  {
    title: "School",
    vocab: [
      ["学校", "School", "Xuéxiào"],
      ["老师", "Teacher", "Lǎoshī"],
      ["学生", "Student", "Xuéshēng"],
      ["书", "Book", "Shū"],
      ["铅笔", "Pencil", "Qiānbǐ"],
      ["教室", "Classroom", "Jiàoshì"],
      ["学习", "Study", "Xuéxí"],
      ["考试", "Exam", "Kǎoshì"],
      ["同学", "Classmate", "Tóngxué"],
      ["毕业", "Graduation", "Bìyè"],
    ],
  },
  {
    title: "Work & Jobs",
    vocab: [
      ["工作", "Work", "Gōngzuò"],
      ["公司", "Company", "Gōngsī"],
      ["医生", "Doctor", "Yīshēng"],
      ["老师", "Teacher", "Lǎoshī"],
      ["工程师", "Engineer", "Gōngchéngshī"],
      ["经理", "Manager", "Jīnglǐ"],
      ["会计", "Accountant", "Kuàijì"],
      ["工资", "Salary", "Gōngzī"],
      ["会议", "Meeting", "Huìyì"],
      ["电话", "Phone", "Diànhuà"],
    ],
  },
  {
    title: "Transport",
    vocab: [
      ["火车", "Train", "Huǒchē"],
      ["公共汽车", "Bus", "Gōnggòng qìchē"],
      ["自行车", "Bicycle", "Zìxíngchē"],
      ["汽车", "Car", "Qìchē"],
      ["飞机", "Airplane", "Fēijī"],
      ["船", "Ship", "Chuán"],
      ["火车站", "Train station", "Huǒchēzhàn"],
      ["机场", "Airport", "Jīchǎng"],
      ["地铁", "Subway", "Dìtiě"],
      ["出租车", "Taxi", "Chūzūchē"],
    ],
  },
  {
    title: "Shopping",
    vocab: [
      ["商店", "Shop", "Shāngdiàn"],
      ["购物", "Shopping", "Gòuwù"],
      ["价格", "Price", "Jiàgé"],
      ["便宜", "Cheap", "Piányí"],
      ["贵", "Expensive", "Guì"],
      ["找零", "Change", "Zhǎolíng"],
      ["收据", "Receipt", "Shōujù"],
      ["袋子", "Bag", "Dàizi"],
      ["打折", "Sale/Discount", "Dǎzhé"],
      ["买", "To buy", "Mǎi"],
    ],
  },
  {
    title: "Restaurant",
    vocab: [
      ["餐厅", "Restaurant", "Cāntīng"],
      ["菜单", "Menu", "Càidān"],
      ["点菜", "Order food", "Diǎncài"],
      ["好吃", "Delicious", "Hǎochī"],
      ["辣", "Spicy", "Là"],
      ["甜", "Sweet", "Tián"],
      ["咸", "Salty", "Xián"],
      ["买单", "Pay the bill", "Mǎidān"],
      ["桌子", "Table", "Zhuōzi"],
      ["服务员", "Waiter", "Fúwùyuán"],
    ],
  },
  {
    title: "Hobbies",
    vocab: [
      ["电影", "Movie", "Diànyǐng"],
      ["音乐", "Music", "Yīnyuè"],
      ["旅游", "Travel", "Lǚyóu"],
      ["烹饪", "Cooking", "Pēngrèn"],
      ["运动", "Sports", "Yùndòng"],
      ["读书", "Reading", "Dúshū"],
      ["写作", "Writing", "Xiězuò"],
      ["唱歌", "Singing", "Chànggē"],
      ["玩耍", "Playing", "Wánshuǎ"],
      ["散步", "Walk", "Sànbù"],
    ],
  },
  {
    title: "Nature",
    vocab: [
      ["山", "Mountain", "Shān"],
      ["海", "Sea", "Hǎi"],
      ["河", "River", "Hé"],
      ["森林", "Forest", "Sēnlín"],
      ["花", "Flower", "Huā"],
      ["树", "Tree", "Shù"],
      ["天空", "Sky", "Tiānkōng"],
      ["月亮", "Moon", "Yuèliàng"],
      ["星星", "Star", "Xīngxīng"],
      ["太阳", "Sun", "Tàiyáng"],
    ],
  },
  {
    title: "Emotions",
    vocab: [
      ["高兴", "Happy", "Gāoxìng"],
      ["难过", "Sad", "Nánguò"],
      ["生气", "Angry", "Shēngqì"],
      ["害怕", "Afraid", "Hàipà"],
      ["开心", "Joyful", "Kāixīn"],
      ["累", "Tired", "Lèi"],
      ["惊讶", "Surprised", "Jīngyà"],
      ["不好意思", "Embarrassed", "Bùhǎoyìsi"],
      ["困", "Sleepy", "Kùn"],
      ["健康", "Healthy", "Jiànkāng"],
    ],
  },
  {
    title: "Health",
    vocab: [
      ["医院", "Hospital", "Yīyuàn"],
      ["药", "Medicine", "Yào"],
      ["疼", "Painful", "Téng"],
      ["生病", "Sick", "Shēngbìng"],
      ["感冒", "Cold", "Gǎnmào"],
      ["发烧", "Fever", "Fāshāo"],
      ["受伤", "Injured", "Shòushāng"],
      ["治疗", "Treatment", "Zhìliáo"],
      ["预防", "Prevention", "Yùfáng"],
      ["健康", "Health", "Jiànkāng"],
    ],
  },
  {
    title: "Emergency",
    vocab: [
      ["帮帮我", "Help me!", "Bāng bāng wǒ"],
      ["救护车", "Ambulance", "Jiùhùchē"],
      ["警察", "Police", "Jǐngchá"],
      ["火灾", "Fire", "Huǒzāi"],
      ["危险", "Danger", "Wēixiǎn"],
      ["安全", "Safe", "Ānquán"],
      ["紧急出口", "Emergency exit", "Jǐnjí chūkǒu"],
      ["手机", "Mobile phone", "Shǒujī"],
      ["迷路了", "Lost", "Mí lù le"],
      ["请帮我", "Please help", "Qǐng bāng wǒ"],
    ],
  },
  {
    title: "Chinese Culture",
    vocab: [
      ["春节", "Spring Festival", "Chūnjié"],
      ["中秋节", "Mid-Autumn Festival", "Zhōngqiūjié"],
      ["红包", "Red envelope", "Hóngbāo"],
      ["饺子", "Dumplings", "Jiǎozi"],
      ["长城", "Great Wall", "Chángchéng"],
      ["功夫", "Kung Fu", "Gōngfū"],
      ["太极拳", "Tai Chi", "Tàijíquán"],
      ["茶文化", "Tea culture", "Chá wénhuà"],
      ["汉字", "Chinese characters", "Hànzì"],
      ["普通话", "Mandarin", "Pǔtōnghuà"],
    ],
  },
  {
    title: "Measure Words",
    vocab: [
      ["个", "General measure", "Gè"],
      ["只", "For small animals", "Zhī"],
      ["本", "For books", "Běn"],
      ["张", "For flat things", "Zhāng"],
      ["件", "For clothing", "Jiàn"],
      ["条", "For long things", "Tiáo"],
      ["杯", "Cup of", "Bēi"],
      ["碗", "Bowl of", "Wǎn"],
      ["块", "Piece/Yuan", "Kuài"],
      ["次", "Time/Occasion", "Cì"],
    ],
  },
  {
    title: "Verbs 1",
    vocab: [
      ["吃", "To eat", "Chī"],
      ["喝", "To drink", "Hē"],
      ["去", "To go", "Qù"],
      ["来", "To come", "Lái"],
      ["看", "To see/watch", "Kàn"],
      ["听", "To listen", "Tīng"],
      ["说", "To speak", "Shuō"],
      ["写", "To write", "Xiě"],
      ["读", "To read", "Dú"],
      ["做", "To do", "Zuò"],
    ],
  },
  {
    title: "Adjectives 1",
    vocab: [
      ["大", "Big", "Dà"],
      ["小", "Small", "Xiǎo"],
      ["新", "New", "Xīn"],
      ["旧", "Old", "Jiù"],
      ["好", "Good", "Hǎo"],
      ["坏", "Bad", "Huài"],
      ["快", "Fast", "Kuài"],
      ["慢", "Slow", "Màn"],
      ["难", "Difficult", "Nán"],
      ["容易", "Easy", "Róngyì"],
    ],
  },
  {
    title: "Directions",
    vocab: [
      ["右", "Right", "Yòu"],
      ["左", "Left", "Zuǒ"],
      ["前", "Front", "Qián"],
      ["后", "Back", "Hòu"],
      ["直走", "Go straight", "Zhí zǒu"],
      ["附近", "Nearby", "Fùjìn"],
      ["远", "Far", "Yuǎn"],
      ["北", "North", "Běi"],
      ["南", "South", "Nán"],
      ["东", "East", "Dōng"],
    ],
  },
  {
    title: "Grammar Patterns",
    vocab: [
      ["是...的", "It is... that", "Shì...de"],
      ["有", "Have/There is", "Yǒu"],
      ["没有", "Don't have", "Méiyǒu"],
      ["在", "At/In/On", "Zài"],
      ["不", "Not/No", "Bù"],
      ["也", "Also/Too", "Yě"],
      ["都", "Both/All", "Dōu"],
      ["很", "Very", "Hěn"],
      ["了", "Change/Completion", "Le"],
      ["吗", "Question marker", "Ma"],
    ],
  },
  {
    title: "Advanced Vocab 1",
    vocab: [
      ["尽管", "Although", "Jǐnguǎn"],
      ["然而", "However", "Rán'ér"],
      ["因此", "Therefore", "Yīncǐ"],
      ["另外", "In addition", "Lìngwài"],
      ["总之", "In summary", "Zǒngzhī"],
      ["毕竟", "After all", "Bìjìng"],
      ["逐渐", "Gradually", "Zhújiàn"],
      ["彻底", "Thoroughly", "Chèdǐ"],
      ["充分", "Fully", "Chōngfèn"],
      ["相当", "Quite/Rather", "Xiāngdāng"],
    ],
  },
  {
    title: "HSK 4 Words",
    vocab: [
      ["竟然", "Unexpectedly", "Jìngrán"],
      ["难怪", "No wonder", "Nánguài"],
      ["万一", "Just in case", "Wànyī"],
      ["总算", "Finally", "Zǒngsuàn"],
      ["按照", "According to", "Ànzhào"],
      ["即使", "Even if", "Jíshǐ"],
      ["况且", "Moreover", "Kuàngqiě"],
      ["既然", "Since (already)", "Jìrán"],
      ["宁可", "Would rather", "Nìngkě"],
      ["尽管如此", "Despite this", "Jǐnguǎn rúcǐ"],
    ],
  },
  {
    title: "HSK 5 Words",
    vocab: [
      ["鉴于", "In view of", "Jiànyú"],
      ["以便", "So that", "Yǐbiàn"],
      ["而且", "Moreover", "Érqiě"],
      ["首先", "First of all", "Shǒuxiān"],
      ["其次", "Secondly", "Qícì"],
      ["此外", "Besides", "Cǐwài"],
      ["总而言之", "To sum up", "Zǒng ér yán zhī"],
      ["相反", "On the contrary", "Xiāngfǎn"],
      ["固然", "Admittedly", "Gùrán"],
      ["反之", "On the other hand", "Fǎn zhī"],
    ],
  },
  {
    title: "Business Chinese",
    vocab: [
      ["合同", "Contract", "Hétóng"],
      ["谈判", "Negotiation", "Tánpàn"],
      ["投资", "Investment", "Tóuzī"],
      ["市场", "Market", "Shìchǎng"],
      ["品牌", "Brand", "Pǐnpái"],
      ["策略", "Strategy", "Cèlüè"],
      ["利润", "Profit", "Lìrùn"],
      ["竞争", "Competition", "Jìngzhēng"],
      ["客户", "Customer", "Kèhù"],
      ["合作", "Cooperation", "Hézuò"],
    ],
  },
  {
    title: "Chengyu 1",
    vocab: [
      ["一石二鸟", "Kill two birds with one stone", "Yī shí èr niǎo"],
      ["半途而废", "Give up halfway", "Bàntú érfèi"],
      ["马到成功", "Immediate success", "Mǎ dào chénggōng"],
      ["一帆风顺", "Plain sailing", "Yī fān fēng shùn"],
      ["百折不挠", "Never give up", "Bǎi zhé bù náo"],
      ["守株待兔", "Wait for windfall", "Shǒu zhū dài tù"],
      ["画蛇添足", "Gild the lily", "Huà shé tiān zú"],
      ["亡羊补牢", "Mend the fold", "Wáng yáng bǔ láo"],
      ["塞翁失马", "A blessing in disguise", "Sài wēng shī mǎ"],
      ["名副其实", "Worthy of the name", "Míng fù qí shí"],
    ],
  },
  {
    title: "Chengyu 2",
    vocab: [
      ["学无止境", "Learning is endless", "Xué wú zhǐjìng"],
      ["不耻下问", "Not ashamed to ask", "Bù chǐ xià wèn"],
      ["温故知新", "Review old, learn new", "Wēn gù zhī xīn"],
      ["博学多才", "Versatile and knowledgeable", "Bó xué duō cái"],
      ["勤能补拙", "Diligence covers weakness", "Qín néng bǔ zhuō"],
      ["有志者事竟成", "Where there's a will", "Yǒu zhì zhě shì jìng chéng"],
      ["功夫不负有心人", "Effort pays off", "Gōngfū bù fù yǒuxīn rén"],
      [
        "千里之行始于足下",
        "Journey of 1000 miles",
        "Qiānlǐ zhī xíng shǐ yú zú xià",
      ],
      ["好学不倦", "Eager to learn", "Hào xué bú juàn"],
      ["活到老学到老", "Never too old to learn", "Huó dào lǎo xué dào lǎo"],
    ],
  },
  {
    title: "Mastery Review",
    vocab: [
      ["词汇", "Vocabulary", "Cíhuì"],
      ["语法", "Grammar", "Yǔfǎ"],
      ["发音", "Pronunciation", "Fāyīn"],
      ["阅读", "Reading", "Yuèdú"],
      ["听力", "Listening", "Tīnglì"],
      ["写作", "Writing", "Xiězuò"],
      ["口语", "Speaking", "Kǒuyǔ"],
      ["翻译", "Translation", "Fānyì"],
      ["掌握", "To master", "Zhǎngwò"],
      ["流利", "Fluent", "Liúlì"],
    ],
  },
];

const kannadaUnits: { title: string; vocab: [string, string, string][] }[] = [
  {
    title: "Greetings",
    vocab: [
      ["ನಮಸ್ಕಾರ", "Hello/Greetings", "Namaskāra"],
      ["ಶುಭೋದಯ", "Good morning", "Śubhodaya"],
      ["ಶುಭ ಸಂಜೆ", "Good evening", "Śubha Sanje"],
      ["ವಿದಾಯ", "Goodbye", "Vidāya"],
      ["ಧನ್ಯವಾದ", "Thank you", "Dhanyavāda"],
      ["ದಯವಿಟ್ಟು", "Please", "Dayaviṭṭu"],
      ["ಹೌದು", "Yes", "Haudu"],
      ["ಇಲ್ಲ", "No", "Illa"],
      ["ಕ್ಷಮಿಸಿ", "Excuse me/Sorry", "Kṣamisi"],
      ["ಸ್ವಾಗತ", "Welcome", "Svāgata"],
    ],
  },
  {
    title: "Numbers",
    vocab: [
      ["ಒಂದು", "One", "Ondu"],
      ["ಎರಡು", "Two", "Eraḍu"],
      ["ಮೂರು", "Three", "Mūru"],
      ["ನಾಲ್ಕು", "Four", "Nālku"],
      ["ಐದು", "Five", "Aidu"],
      ["ಆರು", "Six", "Āru"],
      ["ಏಳು", "Seven", "Ēḷu"],
      ["ಎಂಟು", "Eight", "Eṃṭu"],
      ["ಒಂಬತ್ತು", "Nine", "Ommbattu"],
      ["ಹತ್ತು", "Ten", "Hattu"],
    ],
  },
  {
    title: "Colors",
    vocab: [
      ["ಕೆಂಪು", "Red", "Kempu"],
      ["ನೀಲಿ", "Blue", "Nīli"],
      ["ಹಳದಿ", "Yellow", "Haḷadi"],
      ["ಹಸಿರು", "Green", "Hasiru"],
      ["ಬಿಳಿ", "White", "Biḷi"],
      ["ಕಪ್ಪು", "Black", "Kappu"],
      ["ಕಂದು", "Brown", "Kandu"],
      ["ನೇರಳೆ", "Purple", "Nēraḷe"],
      ["ಗುಲಾಬಿ", "Pink", "Gulābi"],
      ["ಕಿತ್ತಳೆ", "Orange", "Kittalе"],
    ],
  },
  {
    title: "Animals",
    vocab: [
      ["ನಾಯಿ", "Dog", "Nāyi"],
      ["ಬೆಕ್ಕು", "Cat", "Bekku"],
      ["ಹಕ್ಕಿ", "Bird", "Hakki"],
      ["ಮೀನು", "Fish", "Mīnu"],
      ["ಮೊಲ", "Rabbit", "Mola"],
      ["ಕರಡಿ", "Bear", "Karaḍi"],
      ["ಆನೆ", "Elephant", "Āne"],
      ["ಸಿಂಹ", "Lion", "Simha"],
      ["ಕೋತಿ", "Monkey", "Kōti"],
      ["ಕುದುರೆ", "Horse", "Kudure"],
    ],
  },
  {
    title: "Food & Drink",
    vocab: [
      ["ಅನ್ನ", "Rice", "Anna"],
      ["ನೀರು", "Water", "Nīru"],
      ["ಚಹಾ", "Tea", "Cahā"],
      ["ರೊಟ್ಟಿ", "Bread/Roti", "Roṭṭi"],
      ["ಮೊಟ್ಟೆ", "Egg", "Moṭṭe"],
      ["ಮೀನು", "Fish", "Mīnu"],
      ["ಮಾಂಸ", "Meat", "Māmsa"],
      ["ತರಕಾರಿ", "Vegetables", "Tarakāri"],
      ["ಹಣ್ಣು", "Fruit", "Haṇṇu"],
      ["ಇಡ್ಲಿ", "Idli", "Iḍli"],
    ],
  },
  {
    title: "Family",
    vocab: [
      ["ಅಪ್ಪ", "Father", "Appa"],
      ["ಅಮ್ಮ", "Mother", "Amma"],
      ["ಅಣ್ಣ", "Elder brother", "Aṇṇa"],
      ["ಅಕ್ಕ", "Elder sister", "Akka"],
      ["ತಮ್ಮ", "Younger brother", "Tamma"],
      ["ತಂಗಿ", "Younger sister", "Taṅgi"],
      ["ತಾತ", "Grandfather", "Tāta"],
      ["ಅಜ್ಜಿ", "Grandmother", "Ajji"],
      ["ಮಗು", "Child", "Magu"],
      ["ಕುಟುಂಬ", "Family", "Kuṭumba"],
    ],
  },
  {
    title: "Body Parts",
    vocab: [
      ["ತಲೆ", "Head", "Tale"],
      ["ಕಣ್ಣು", "Eye", "Kaṇṇu"],
      ["ಮೂಗು", "Nose", "Mūgu"],
      ["ಬಾಯಿ", "Mouth", "Bāyi"],
      ["ಕೈ", "Hand", "Kai"],
      ["ಕಾಲು", "Leg/Foot", "Kālu"],
      ["ದೇಹ", "Body", "Dēha"],
      ["ಕೂದಲು", "Hair", "Kūdalu"],
      ["ಕಿವಿ", "Ear", "Kivi"],
      ["ಭುಜ", "Shoulder", "Bhuja"],
    ],
  },
  {
    title: "Weather",
    vocab: [
      ["ಬಿಸಿಲು", "Sunny/Heat", "Bisilu"],
      ["ಮೋಡ", "Cloud", "Mōḍa"],
      ["ಮಳೆ", "Rain", "Maḷe"],
      ["ಹಿಮ", "Snow", "Hima"],
      ["ಗಾಳಿ", "Wind", "Gāḷi"],
      ["ಬಿಸಿ", "Hot", "Bisi"],
      ["ಚಳಿ", "Cold", "Caḷi"],
      ["ಹವಾಮಾನ", "Weather", "Havāmāna"],
      ["ಗುಡುಗು", "Thunder", "Guḍugu"],
      ["ಕಾಮನಬಿಲ್ಲು", "Rainbow", "Kāmanabillu"],
    ],
  },
  {
    title: "Time",
    vocab: [
      ["ಒಂದು ಗಂಟೆ", "One o'clock", "Ondu Gaṃṭe"],
      ["ಎರಡು ಗಂಟೆ", "Two o'clock", "Eraḍu Gaṃṭe"],
      ["ಬೆಳಗ್ಗೆ", "Morning", "Beḷagge"],
      ["ಸಂಜೆ", "Evening", "Sanje"],
      ["ಈಗ", "Now", "Īga"],
      ["ಇಂದು", "Today", "Iṃdu"],
      ["ನಾಳೆ", "Tomorrow", "Nāḷe"],
      ["ನಿನ್ನೆ", "Yesterday", "Ninne"],
      ["ಪ್ರತಿದಿನ", "Everyday", "Pratidina"],
      ["ಸಮಯ", "Time", "Samaya"],
    ],
  },
  {
    title: "Days of Week",
    vocab: [
      ["ಭಾನುವಾರ", "Sunday", "Bhānuvāra"],
      ["ಸೋಮವಾರ", "Monday", "Sōmavāra"],
      ["ಮಂಗಳವಾರ", "Tuesday", "Maṃgaḷavāra"],
      ["ಬುಧವಾರ", "Wednesday", "Budhavāra"],
      ["ಗುರುವಾರ", "Thursday", "Guruvāra"],
      ["ಶುಕ್ರವಾರ", "Friday", "Śukravāra"],
      ["ಶನಿವಾರ", "Saturday", "Śanivāra"],
      ["ವಾರಾಂತ್ಯ", "Weekend", "Vārāntya"],
      ["ಕೆಲಸದ ದಿನ", "Weekday", "Kelasada Dina"],
      ["ಮುಂದಿನ ವಾರ", "Next week", "Muṃdina Vāra"],
    ],
  },
  {
    title: "Months",
    vocab: [
      ["ಜನವರಿ", "January", "Janavari"],
      ["ಫೆಬ್ರವರಿ", "February", "Phebravari"],
      ["ಮಾರ್ಚ್", "March", "Mārc"],
      ["ಏಪ್ರಿಲ್", "April", "Ēpril"],
      ["ಮೇ", "May", "Mē"],
      ["ಜೂನ್", "June", "Jūn"],
      ["ಜುಲೈ", "July", "Julai"],
      ["ಆಗಸ್ಟ್", "August", "Āgasṭ"],
      ["ಸೆಪ್ಟೆಂಬರ್", "September", "Sepṭeṃbar"],
      ["ಅಕ್ಟೋಬರ್", "October", "Akṭōbar"],
    ],
  },
  {
    title: "Seasons",
    vocab: [
      ["ವಸಂತ", "Spring", "Vasaṃta"],
      ["ಬೇಸಿಗೆ", "Summer", "Bēsige"],
      ["ಶರತ್ಕಾಲ", "Autumn", "Śaratkāla"],
      ["ಚಳಿಗಾಲ", "Winter", "Caḷigāla"],
      ["ಋತು", "Season", "R̥tu"],
      ["ಬೆಚ್ಚಗೆ", "Warm", "Beccage"],
      ["ತಂಪಾಗಿ", "Cool", "Taṃpāgi"],
      ["ಮಳೆಗಾಲ", "Rainy season", "Maḷegāla"],
      ["ಬೆಳೆ", "Crop", "Beḷe"],
      ["ಸೂರ್ಯ", "Sun", "Sūrya"],
    ],
  },
  {
    title: "Clothing",
    vocab: [
      ["ಅಂಗಿ", "Shirt", "Aṃgi"],
      ["ಪ್ಯಾಂಟ್", "Pants", "Pyāṃṭ"],
      ["ಚಪ್ಪಲಿ", "Sandals", "Cappali"],
      ["ಟೋಪಿ", "Hat", "Ṭōpi"],
      ["ಕೋಟು", "Coat", "Kōṭu"],
      ["ಸೀರೆ", "Saree", "Sīre"],
      ["ಸಾಕ್ಸ್", "Socks", "Sāks"],
      ["ಶಾಲು", "Shawl", "Śālu"],
      ["ಕೈಚೀಲ", "Gloves", "Kaicīla"],
      ["ಸೂಟ್", "Suit", "Sūṭ"],
    ],
  },
  {
    title: "Home & Rooms",
    vocab: [
      ["ಮನೆ", "House", "Mane"],
      ["ಕೋಣೆ", "Room", "Kōṇe"],
      ["ಅಡಿಗೆ ಮನೆ", "Kitchen", "Aḍige Mane"],
      ["ಹಾಲ್", "Hall/Living room", "Hāl"],
      ["ಮಲಗುವ ಕೋಣೆ", "Bedroom", "Malaguva Kōṇe"],
      ["ಸ್ನಾನ ಮನೆ", "Bathroom", "Snāna Mane"],
      ["ಕಿಟಕಿ", "Window", "Kiṭaki"],
      ["ಬಾಗಿಲು", "Door", "Bāgilu"],
      ["ಮೇಜು", "Table", "Mēju"],
      ["ಕುರ್ಚಿ", "Chair", "Kurci"],
    ],
  },
  {
    title: "School",
    vocab: [
      ["ಶಾಲೆ", "School", "Śāle"],
      ["ಶಿಕ್ಷಕ", "Teacher", "Śikṣaka"],
      ["ವಿದ್ಯಾರ್ಥಿ", "Student", "Vidyārthi"],
      ["ಪುಸ್ತಕ", "Book", "Pustaka"],
      ["ಪೆನ್ಸಿಲ್", "Pencil", "Pensil"],
      ["ತರಗತಿ", "Classroom", "Taragati"],
      ["ಅಧ್ಯಯನ", "Study", "Adhyayana"],
      ["ಪರೀಕ್ಷೆ", "Exam", "Parīkṣe"],
      ["ಸಹಪಾಠಿ", "Classmate", "Sahapāṭhi"],
      ["ಪದವಿ", "Degree", "Padavi"],
    ],
  },
  {
    title: "Work & Jobs",
    vocab: [
      ["ಕೆಲಸ", "Work", "Kelasa"],
      ["ಕಂಪನಿ", "Company", "Kampani"],
      ["ವೈದ್ಯ", "Doctor", "Vaidya"],
      ["ಶಿಕ್ಷಕ", "Teacher", "Śikṣaka"],
      ["ಇಂಜಿನಿಯರ್", "Engineer", "Iṃjiniyar"],
      ["ಮ್ಯಾನೇಜರ್", "Manager", "Myānējar"],
      ["ಲೆಕ್ಕಿಗ", "Accountant", "Lekkiga"],
      ["ಸಂಬಳ", "Salary", "Sambaḷa"],
      ["ಸಭೆ", "Meeting", "Sabhe"],
      ["ದೂರವಾಣಿ", "Phone", "Dūravāṇi"],
    ],
  },
  {
    title: "Transport",
    vocab: [
      ["ರೈಲು", "Train", "Railu"],
      ["ಬಸ್", "Bus", "Bas"],
      ["ಸೈಕಲ್", "Bicycle", "Saikal"],
      ["ಕಾರು", "Car", "Kāru"],
      ["ವಿಮಾನ", "Airplane", "Vimāna"],
      ["ಹಡಗು", "Ship", "Haḍagu"],
      ["ನಿಲ್ದಾಣ", "Station", "Nildāṇa"],
      ["ವಿಮಾನ ನಿಲ್ದಾಣ", "Airport", "Vimāna Nildāṇa"],
      ["ಮೆಟ್ರೋ", "Metro", "Meṭrō"],
      ["ಟ್ಯಾಕ್ಸಿ", "Taxi", "Ṭyāksi"],
    ],
  },
  {
    title: "Shopping",
    vocab: [
      ["ಅಂಗಡಿ", "Shop", "Aṃgaḍi"],
      ["ಶಾಪಿಂಗ್", "Shopping", "Śāpiṃg"],
      ["ಬೆಲೆ", "Price", "Bele"],
      ["ಅಗ್ಗ", "Cheap", "Agga"],
      ["ದುಬಾರಿ", "Expensive", "Dubāri"],
      ["ಚಿಲ್ಲರೆ", "Change", "Cillare"],
      ["ರಸೀದಿ", "Receipt", "Rasīdi"],
      ["ಚೀಲ", "Bag", "Cīla"],
      ["ರಿಯಾಯಿತಿ", "Discount", "Riyāyiti"],
      ["ಕೊಳ್ಳು", "To buy", "Koḷḷu"],
    ],
  },
  {
    title: "Restaurant",
    vocab: [
      ["ಹೋಟೆಲ್", "Restaurant", "Hōṭel"],
      ["ಮೆನು", "Menu", "Menu"],
      ["ಆರ್ಡರ್", "Order", "Ārḍar"],
      ["ರುಚಿಯಾದ", "Delicious", "Ruciyāda"],
      ["ಖಾರ", "Spicy", "Khāra"],
      ["ಸಿಹಿ", "Sweet", "Sihi"],
      ["ಉಪ್ಪು", "Salty", "Uppu"],
      ["ಬಿಲ್", "Bill", "Bil"],
      ["ಟೇಬಲ್", "Table", "Ṭēbal"],
      ["ಸೇವಕ", "Waiter", "Sēvaka"],
    ],
  },
  {
    title: "Hobbies",
    vocab: [
      ["ಸಿನಿಮಾ", "Movie", "Sinimā"],
      ["ಸಂಗೀತ", "Music", "Saṃgīta"],
      ["ಪ್ರವಾಸ", "Travel", "Pravāsa"],
      ["ಅಡುಗೆ", "Cooking", "Aḍuge"],
      ["ಕ್ರೀಡೆ", "Sports", "Krīḍe"],
      ["ಓದು", "Reading", "Ōdu"],
      ["ಬರೆ", "Writing", "Bare"],
      ["ಹಾಡು", "Singing", "Hāḍu"],
      ["ಆಟ", "Play", "Āṭa"],
      ["ವಾಕಿಂಗ್", "Walking", "Vākiṃg"],
    ],
  },
  {
    title: "Nature",
    vocab: [
      ["ಬೆಟ್ಟ", "Mountain", "Beṭṭa"],
      ["ಸಮುದ್ರ", "Sea", "Samudra"],
      ["ನದಿ", "River", "Nadi"],
      ["ಕಾಡು", "Forest", "Kāḍu"],
      ["ಹೂವು", "Flower", "Hūvu"],
      ["ಮರ", "Tree", "Mara"],
      ["ಆಕಾಶ", "Sky", "Ākāśa"],
      ["ಚಂದ್ರ", "Moon", "Caṃdra"],
      ["ನಕ್ಷತ್ರ", "Star", "Nakṣatra"],
      ["ಸೂರ್ಯ", "Sun", "Sūrya"],
    ],
  },
  {
    title: "Emotions",
    vocab: [
      ["ಸಂತೋಷ", "Happy", "Saṃtōṣa"],
      ["ದುಃಖ", "Sad", "Duḥkha"],
      ["ಕೋಪ", "Angry", "Kōpa"],
      ["ಭಯ", "Fear", "Bhaya"],
      ["ಆನಂದ", "Joy", "Ānaṃda"],
      ["ದಣಿದ", "Tired", "Daṇida"],
      ["ಆಶ್ಚರ್ಯ", "Surprised", "Āścarya"],
      ["ನಾಚಿಕೆ", "Embarrassed", "Nācike"],
      ["ನಿದ್ದೆ", "Sleepy", "Nidde"],
      ["ಆರೋಗ್ಯ", "Healthy", "Ārōgya"],
    ],
  },
  {
    title: "Health",
    vocab: [
      ["ಆಸ್ಪತ್ರೆ", "Hospital", "Āspatre"],
      ["ಔಷಧ", "Medicine", "Auṣadha"],
      ["ನೋವು", "Pain", "Nōvu"],
      ["ಅನಾರೋಗ್ಯ", "Illness", "Anārōgya"],
      ["ಶೀತ", "Cold", "Śīta"],
      ["ಜ್ವರ", "Fever", "Jvara"],
      ["ಗಾಯ", "Injury", "Gāya"],
      ["ಚಿಕಿತ್ಸೆ", "Treatment", "Cikitse"],
      ["ತಡೆ", "Prevention", "Taḍe"],
      ["ಆರೋಗ್ಯ", "Health", "Ārōgya"],
    ],
  },
  {
    title: "Emergency",
    vocab: [
      ["ಸಹಾಯ ಮಾಡಿ", "Help!", "Sahāya Māḍi"],
      ["ಆಂಬ್ಯುಲೆನ್ಸ್", "Ambulance", "Āṃbyulens"],
      ["ಪೊಲೀಸ್", "Police", "Polīs"],
      ["ಬೆಂಕಿ", "Fire", "Beṃki"],
      ["ಅಪಾಯ", "Danger", "Apāya"],
      ["ಸುರಕ್ಷಿತ", "Safe", "Surakṣita"],
      ["ತುರ್ತು ನಿರ್ಗಮನ", "Emergency exit", "Turtu Nirgamana"],
      ["ಮೊಬೈಲ್", "Mobile phone", "Mobail"],
      ["ದಾರಿ ತಪ್ಪಿದ", "Lost", "Dāri Tappida"],
      ["ನೆರವು", "Help/Aid", "Neravu"],
    ],
  },
  {
    title: "Karnataka Culture",
    vocab: [
      ["ಯುಗಾದಿ", "Yugadi festival", "Yugādi"],
      ["ದಸರಾ", "Dasara festival", "Dasarā"],
      ["ರಂಗೋಲಿ", "Rangoli", "Raṃgōli"],
      ["ದೋಸೆ", "Dosa", "Dōse"],
      ["ಸಂಪಿಗೆ", "Champak flower", "Saṃpige"],
      ["ಕನ್ನಡ", "Kannada language", "Kannaḍa"],
      ["ವೀಣೆ", "Veena", "Vīṇe"],
      ["ಭರತನಾಟ್ಯ", "Bharatanatyam", "Bharatanāṭya"],
      ["ಮೈಸೂರು", "Mysuru city", "Maisūru"],
      ["ಹಂಪಿ", "Hampi heritage", "Hampi"],
    ],
  },
  {
    title: "Verbs 1",
    vocab: [
      ["ತಿನ್ನು", "To eat", "Tinnu"],
      ["ಕುಡಿ", "To drink", "Kuḍi"],
      ["ಹೋಗು", "To go", "Hōgu"],
      ["ಬಾ", "To come", "Bā"],
      ["ನೋಡು", "To see", "Nōḍu"],
      ["ಕೇಳು", "To listen", "Kēḷu"],
      ["ಮಾತಾಡು", "To speak", "Mātāḍu"],
      ["ಬರೆ", "To write", "Bare"],
      ["ಓದು", "To read", "Ōdu"],
      ["ಮಾಡು", "To do", "Māḍu"],
    ],
  },
  {
    title: "Adjectives 1",
    vocab: [
      ["ದೊಡ್ಡ", "Big", "Doḍḍa"],
      ["ಚಿಕ್ಕ", "Small", "Cikka"],
      ["ಹೊಸ", "New", "Hosa"],
      ["ಹಳೆ", "Old", "Haḷe"],
      ["ಒಳ್ಳೆ", "Good", "Oḷḷe"],
      ["ಕೆಟ್ಟ", "Bad", "Keṭṭa"],
      ["ವೇಗ", "Fast", "Vēga"],
      ["ನಿಧಾನ", "Slow", "Nidhāna"],
      ["ಕಷ್ಟ", "Difficult", "Kaṣṭa"],
      ["ಸುಲಭ", "Easy", "Sulabha"],
    ],
  },
  {
    title: "Directions",
    vocab: [
      ["ಬಲ", "Right", "Bala"],
      ["ಎಡ", "Left", "Eḍa"],
      ["ಮುಂದೆ", "Forward", "Muṃde"],
      ["ಹಿಂದೆ", "Behind", "Hiṃde"],
      ["ನೇರ", "Straight", "Nēra"],
      ["ಹತ್ತಿರ", "Near", "Hattira"],
      ["ದೂರ", "Far", "Dūra"],
      ["ಉತ್ತರ", "North", "Uttara"],
      ["ದಕ್ಷಿಣ", "South", "Dakṣiṇa"],
      ["ಪೂರ್ವ", "East", "Pūrva"],
    ],
  },
  {
    title: "Grammar Basics",
    vocab: [
      ["ನಾನು", "I", "Nānu"],
      ["ನೀನು", "You", "Nīnu"],
      ["ಅವನು", "He", "Avanu"],
      ["ಅವಳು", "She", "Avaḷu"],
      ["ನಾವು", "We", "Nāvu"],
      ["ಅವರು", "They", "Avaru"],
      ["ಇದು", "This", "Idu"],
      ["ಅದು", "That", "Adu"],
      ["ಏನು", "What", "Ēnu"],
      ["ಯಾರು", "Who", "Yāru"],
    ],
  },
  {
    title: "Advanced Verbs",
    vocab: [
      ["ನೆನಪಿಡು", "To remember", "Nenapidu"],
      ["ಮರೆ", "To forget", "Mare"],
      ["ಕಲಿಸು", "To teach", "Kalisu"],
      ["ಕಲಿ", "To learn", "Kali"],
      ["ಅರ್ಥ", "To understand", "Artha"],
      ["ತಿಳಿ", "To know", "Tiḷi"],
      ["ಯೋಚಿಸು", "To think", "Yōcisu"],
      ["ನಿರ್ಧರಿಸು", "To decide", "Nirdharisu"],
      ["ಬದಲಾಯಿಸು", "To change", "Badalāyisu"],
      ["ಬಳಸು", "To use", "Baḷasu"],
    ],
  },
  {
    title: "Advanced Adjectives",
    vocab: [
      ["ಅದ್ಭುತ", "Wonderful", "Adbhuta"],
      ["ಮುಖ್ಯ", "Important", "Mukhya"],
      ["ಅಪರೂಪ", "Rare", "Aparūpa"],
      ["ಮುದ್ದು", "Cute", "Muddu"],
      ["ಸುಂದರ", "Beautiful", "Suṃdara"],
      ["ಕಠಿಣ", "Strict", "Kaṭhiṇa"],
      ["ಶಾಂತ", "Calm", "Śāṃta"],
      ["ಗಂಭೀರ", "Serious", "Gaṃbhīra"],
      ["ಚತುರ", "Clever", "Catura"],
      ["ದಯಾಳು", "Kind", "Dayāḷu"],
    ],
  },
  {
    title: "Society & Life",
    vocab: [
      ["ರಾಜಕೀಯ", "Politics", "Rājakīya"],
      ["ಆರ್ಥಿಕ", "Economic", "Ārthika"],
      ["ಸಮಾಜ", "Society", "Samāja"],
      ["ಸಮಸ್ಯೆ", "Problem", "Samasye"],
      ["ಪರಿಹಾರ", "Solution", "Parihāra"],
      ["ಪರಿಸರ", "Environment", "Parisara"],
      ["ಶಾಂತಿ", "Peace", "Śāṃti"],
      ["ಸ್ವಾತಂತ್ರ್ಯ", "Freedom", "Svātaṃtrya"],
      ["ಸಮಾನತೆ", "Equality", "Samānate"],
      ["ಪ್ರಗತಿ", "Progress", "Pragati"],
    ],
  },
  {
    title: "Literature & Arts",
    vocab: [
      ["ಕಾವ್ಯ", "Poetry", "Kāvya"],
      ["ಕಾದಂಬರಿ", "Novel", "Kādambari"],
      ["ನಾಟಕ", "Drama", "Nāṭaka"],
      ["ಚಿತ್ರಕಲೆ", "Painting", "Citrakale"],
      ["ಶಿಲ್ಪಕಲೆ", "Sculpture", "Śilpakale"],
      ["ನೃತ್ಯ", "Dance", "Nr̥tya"],
      ["ಸಂಗೀತ", "Music", "Saṃgīta"],
      ["ಸಾಹಿತ್ಯ", "Literature", "Sāhitya"],
      ["ಭಾಷೆ", "Language", "Bhāṣe"],
      ["ಕನ್ನಡ ಸಾಹಿತ್ಯ", "Kannada literature", "Kannaḍa Sāhitya"],
    ],
  },
  {
    title: "Proverbs 1",
    vocab: [
      ["ಕಲಿ ಕಲಿ ಕಲಿ", "Learn, learn, learn", "Kali kali kali"],
      ["ಶ್ರಮವೇ ಶಕ್ತಿ", "Work is power", "Śramavē Śakti"],
      ["ಜ್ಞಾನವೇ ಬೆಳಕು", "Knowledge is light", "Jñānavē Beḷaku"],
      ["ಸತ್ಯ ಗೆಲ್ಲುತ್ತದೆ", "Truth prevails", "Satya Gelluttade"],
      ["ಐಕ್ಯತೆ ಬಲ", "Unity is strength", "Aikyate Bala"],
      ["ಸಾಧನೆಯೇ ಜೀವನ", "Achievement is life", "Sādhane Jīvana"],
      ["ವಿದ್ಯೆ ಅಮರ", "Education is eternal", "Vidye Amara"],
      ["ಸೇವೆಯೇ ಧರ್ಮ", "Service is duty", "Sēveyē Dharma"],
      ["ನಂಬಿಕೆ ಅಗತ್ಯ", "Trust is essential", "Naṃbike Agatya"],
      ["ಪ್ರೀತಿ ದೊಡ್ಡದು", "Love is great", "Prīti Doḍḍadu"],
    ],
  },
  {
    title: "Advanced Grammar",
    vocab: [
      ["ಆದ್ದರಿಂದ", "Therefore", "Āddariṃda"],
      ["ಆದರೆ", "But/However", "Ādare"],
      ["ಅಲ್ಲದೆ", "Moreover", "Allade"],
      ["ಅದಕ್ಕಾಗಿ", "For that reason", "Adakkāgi"],
      ["ಹಾಗೆಯೇ", "Similarly", "Hāgeyē"],
      ["ಏಕೆಂದರೆ", "Because", "Ēkeṃdare"],
      ["ಆದ್ಯಾಗಿ", "Therefore", "Ādyāgi"],
      ["ಅಂದರೆ", "Meaning/That is", "Aṃdare"],
      ["ನಂತರ", "After", "Naṃtara"],
      ["ಮೊದಲು", "Before/First", "Modalu"],
    ],
  },
  {
    title: "Mastery Review",
    vocab: [
      ["ಶಬ್ದ ಭಂಡಾರ", "Vocabulary", "Śabda Bhaṃḍāra"],
      ["ವ್ಯಾಕರಣ", "Grammar", "Vyākaraṇa"],
      ["ಉಚ್ಚಾರಣೆ", "Pronunciation", "Uccāraṇe"],
      ["ಓದುವಿಕೆ", "Reading", "Ōduvike"],
      ["ಕೇಳುವಿಕೆ", "Listening", "Kēḷuvike"],
      ["ಬರವಣಿಗೆ", "Writing", "Barava ṇige"],
      ["ಮಾತನಾಡುವಿಕೆ", "Speaking", "Mātanāḍuvike"],
      ["ಅನುವಾದ", "Translation", "Anuvāda"],
      ["ಕಲಿಕೆ", "Learning", "Kalike"],
      ["ನಿಪುಣ", "Proficient", "Nipuṇa"],
    ],
  },
];

function makeMcq(
  word: string,
  meaning: string,
  allVocab: [string, string, string][],
): McqExercise {
  const wrong = allVocab
    .filter((v) => v[0] !== word)
    .sort(() => Math.random() - 0.5)
    .slice(0, 3)
    .map((v) => v[1]);
  const options = [meaning, ...wrong].sort(() => Math.random() - 0.5);
  return {
    type: "mcq",
    question: `What does "${word}" mean?`,
    options,
    answer: meaning,
  };
}

function makeFill(
  word: string,
  meaning: string,
  pronunciation: string,
): FillExercise {
  return {
    type: "fill",
    sentence: `The word for "${meaning}" is ___`,
    answer: word,
    hint: `Pronunciation: ${pronunciation}`,
  };
}

function makeTranslate(word: string, meaning: string): TranslateExercise {
  return {
    type: "translate",
    source: meaning,
    answer: word,
    hint: "Think about how this word sounds",
  };
}

const levelCache = new Map<string, Level[]>();

export function getLevels(language: Language): Level[] {
  if (levelCache.has(language)) return levelCache.get(language)!;

  const units =
    language === "japanese"
      ? japaneseUnits
      : language === "mandarin"
        ? mandarinUnits
        : kannadaUnits;
  const levels: Level[] = [];
  let levelId = 1;

  // 50 units × 10 levels = 500 levels
  for (let unitIdx = 0; unitIdx < 50; unitIdx++) {
    const unit = units[unitIdx % units.length];
    const unitNumber = unitIdx + 1;
    const unitTitle =
      unitIdx < units.length
        ? unit.title
        : `${unit.title} — Advanced ${Math.floor(unitIdx / units.length) + 1}`;
    const allVocabForUnit = unit.vocab;

    for (let levelInUnit = 0; levelInUnit < 10; levelInUnit++) {
      const vocabIndex = levelInUnit % allVocabForUnit.length;
      const vocabSlice = allVocabForUnit.slice(vocabIndex, vocabIndex + 4);
      if (vocabSlice.length < 4)
        vocabSlice.push(...allVocabForUnit.slice(0, 4 - vocabSlice.length));

      const exercises: Exercise[] = [];
      const levelTypes: ExerciseType[] = [
        "vocab",
        "mcq",
        "fill",
        "match",
        "translate",
      ];
      const levelType = levelTypes[levelInUnit % levelTypes.length];

      // Always start with a vocab intro
      exercises.push({
        type: "vocab",
        word: vocabSlice[0][0],
        translation: vocabSlice[0][1],
        pronunciation: vocabSlice[0][2],
      });

      // MCQ
      exercises.push(
        makeMcq(vocabSlice[1][0], vocabSlice[1][1], allVocabForUnit),
      );

      // Fill in the blank
      exercises.push(
        makeFill(vocabSlice[2][0], vocabSlice[2][1], vocabSlice[2][2]),
      );

      // Match pairs
      exercises.push({
        type: "match",
        pairs: vocabSlice.map((v) => ({ word: v[0], translation: v[1] })),
      });

      // Translate
      exercises.push(makeTranslate(vocabSlice[3][0], vocabSlice[3][1]));

      const levelTitles = [
        "Introduction",
        "Practice",
        "Review",
        "Challenge",
        "Mastery",
        "Speed Round",
        "Deep Dive",
        "Quiz",
        "Fluency",
        "Expert",
      ];

      levels.push({
        id: levelId++,
        unit: unitNumber,
        unitTitle,
        levelTitle: levelTitles[levelInUnit],
        type: levelType,
        xpReward: Math.round(10 + levelId * 0.1),
        exercises,
      });
    }
  }

  levelCache.set(language, levels);
  return levels;
}

export function getLevel(
  language: Language,
  levelId: number,
): Level | undefined {
  return getLevels(language).find((l) => l.id === levelId);
}

export const LANGUAGE_INFO: Record<
  Language,
  { name: string; flag: string; nativeName: string }
> = {
  japanese: { name: "Japanese", flag: "🇯🇵", nativeName: "日本語" },
  mandarin: { name: "Mandarin", flag: "🇨🇳", nativeName: "普通话" },
  kannada: { name: "Kannada", flag: "🇮🇳", nativeName: "ಕನ್ನಡ" },
};
